---
title: "mental_health"
output: html_document
date: '2022-06-04'
---

```{r}

```



```{r setup, include=FALSE}
options(scipen=999)

#calling library
library(tidyverse)
library(shiny)
library(readr)
library(ggplot2)
library(tidyr)
library(interactions)
library(dplyr)
```



```{r cars}


#import your .csv file to your Global Environment
survey_dataset <- read.csv("mh_survey.csv", header = TRUE, sep= ",") #.csv as df
survey_dataset
#adding ID column
survey_dataset <- tibble::rowid_to_column(survey_dataset, "ID")
```

## Including Plots



```{r pressure, echo=FALSE}
survey_dataset %>% count(Gender)
survey_dataset %>% count(no_employees)
survey_dataset %>% count(Age)
```



```{r}
#replace specific value for specific case
str(survey_dataset)

#replacing values for garbled entiries
new_survey_dataset <- survey_dataset

```

```{r}
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 545, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 554, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 391, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 990, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 452, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 388, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 778, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 350, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 819, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 361, "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1186, "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 73, "trans-F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 806, "trans-F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 683, "trans-F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1018, "trans-F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 307, "trans-F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 99, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 220, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 933, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 977, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1232, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 627, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 57, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 882, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 196, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 56, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1047, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 629, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 777, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1235, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Make", "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Male ", "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Man", "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 94, "trans-M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 414, NA, Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 417, NA, Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1128, NA, Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 391, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 716, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 1128, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 735, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 990, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 1091, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 365, 32, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 144, 29, Age))

#gender
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "female", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Female", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Female ", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Woman", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "woman", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "f", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Cis Female", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "cis-female/femme", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Female (cis)", "F", Gender))


new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Male", "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "male", "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "m", "M", Gender))

```



```{r}
#self_employed
new_survey_dataset <- new_survey_dataset %>% mutate(self_employed = ifelse(self_employed == "No", 0, self_employed))
new_survey_dataset$self_employed[new_survey_dataset$self_employed == "Yes"] <- 1

#num_employees
new_survey_dataset$no_employees[new_survey_dataset$no_employees == "45809"] <- "6-25"
new_survey_dataset$no_employees[new_survey_dataset$no_employees == "44682"] <- "1-5"
```




```{r}
# The default names are not very descriptive (changing col. names)

colnames(new_survey_dataset)
colnames(new_survey_dataset) <- c("id", "timestamp", "age", "gender", "country", "US_state", "self_employed", "family_history",
                                  "treatment_seek", "work_interference", "num_employees", "remote_work", "tech_company", "employer_benefits",
                                  "provided_care_options", "employee_wellness_program", "provided_seek_help", "anonymity_protection", "medical_leave_mh",
                                  "mental_health_neg_consequence", "phys_health_neg_consequence", "discussing_mh_coworkers", "discussing_mh_supervisor",
                                  "mentalhealthinterview", "phys_health_interview", "mental_vs_physical", "obs_consequence", "comments")

# Better names!
```




```{r}
#checking datas in specific columns
str(new_survey_dataset)
new_survey_dataset %>% distinct(gender)
new_survey_dataset %>% count(gender)
new_survey_dataset %>% count(num_employees)
new_survey_dataset %>% count(timestamp)
new_survey_dataset %>% count(US_state)
new_survey_dataset %>% count(age)
```



```{r}
#plotting
#timestamp 27.08.2014, age- work_interference (country=United States)
new_survey_dataset %>% filter(timestamp == "27.08.2014", country=="United States") %>% 
  mutate(age = age / 1000000) %>% 
  ggplot()+
  geom_point(aes(age, work_interference, color= gender))+
  facet_wrap(~ gender)+
  scale_x_log10()
```

```{r}

#treatment_seek
qplot(x=treatment_seek, data = new_survey_dataset, geom = "bar")

#histogram
base.plot <- ggplot(new_survey_dataset, aes(x = age)) +
  xlab("Employee Age")+
  scale_x_continuous(limits = c(0, 70))
base.plot + geom_histogram()
base.plot + geom_histogram(aes(fill = gender), bins=5)
base.plot + geom_density(aes(fill = gender), alpha = 0.5, adjust=20)
```



