---
title: "mental_health"
output: html_document
date: '2022-06-04'
---

```{r}

```



```{r setup, include=FALSE}
options(scipen=999)

#calling library
library(caret)
library(tidyverse)
library(shiny)
library(readr)
library(ggplot2)
library(tidyr)
library(interactions)
library(dplyr)
library(skimr)
```



```{r cars}


#import your .csv file to your Global Environment
survey_dataset <- read.csv("mh_survey.csv", header = TRUE, sep= ",") #.csv as df

#adding ID column
survey_dataset <- tibble::rowid_to_column(survey_dataset, "ID")
```

## Including Plots




```{r pressure, echo=FALSE}
skimmed <- skim(survey_dataset)
skimmed
```



```{r}

#replacing values for garbled entiries
new_survey_dataset <- survey_dataset

```

```{r}
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 545, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 554, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 391, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 990, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 452, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 388, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 778, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 350, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 819, "Non", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 361, "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1186, "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 73, "trans-F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 806, "trans-F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 683, "trans-F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1018, "trans-F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 307, "trans-F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 99, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 220, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 933, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 977, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1232, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 627, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 57, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 882, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 196, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 56, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1047, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 629, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 777, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1235, "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Make", "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Male ", "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Man", "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 94, "trans-M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 414, NA, Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 417, NA, Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(ID == 1128, NA, Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 391, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 716, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 1128, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 735, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 990, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 1091, NA, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 365, 32, Age))
new_survey_dataset <- new_survey_dataset %>% mutate(Age = ifelse(ID == 144, 29, Age))

#gender
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "female", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Female", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Female ", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Woman", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "woman", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "f", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Cis Female", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "cis-female/femme", "F", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Female (cis)", "F", Gender))


new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "Male", "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "male", "M", Gender))
new_survey_dataset <- new_survey_dataset %>% mutate(Gender = ifelse(Gender == "m", "M", Gender))

```



```{r}
#self_employed
new_survey_dataset <- new_survey_dataset %>% mutate(self_employed = ifelse(self_employed == "No", 0, self_employed))
new_survey_dataset$self_employed[new_survey_dataset$self_employed == "Yes"] <- 1

#num_employees
new_survey_dataset$no_employees[new_survey_dataset$no_employees == "45809"] <- "6-25"
new_survey_dataset$no_employees[new_survey_dataset$no_employees == "44682"] <- "1-5"
```




```{r}
# The default names are not very descriptive (changing col. names)

colnames(new_survey_dataset)
colnames(new_survey_dataset) <- c("id", "timestamp", "age", "gender", "country", "US_state", "self_employed", "family_history",
                                  "treatment_seek", "work_interference", "num_employees", "remote_work", "tech_company", "employer_benefits",
                                  "provided_care_options", "employee_wellness_program", "provided_seek_help", "anonymity_protection", "medical_leave_mh",
                                  "mental_health_neg_consequence", "phys_health_neg_consequence", "discussing_mh_coworkers", "discussing_mh_supervisor",
                                  "mentalhealthinterview", "phys_health_interview", "mental_vs_physical", "obs_consequence", "comments")

# Better names!
```







```{r}
#plotting
#timestamp 27.08.2014, age- work_interference (country=United States)
new_survey_dataset %>% filter(timestamp == "27.08.2014", country=="United States") %>% 
  mutate(age = age / 1000000) %>% 
  ggplot()+
  geom_point(aes(age, work_interference, color= gender))+
  facet_wrap(~ gender)+
  scale_x_log10()
```





```{r}

#treatment_seek
qplot(x=treatment_seek, data = new_survey_dataset, geom = "bar")

#histogram
base.plot <- ggplot(new_survey_dataset, aes(x = age)) +
  xlab("Employee Age")+
  scale_x_continuous(limits = c(0, 70))
base.plot + geom_histogram()
base.plot + geom_histogram(aes(fill = gender), bins=5)
base.plot + geom_density(aes(fill = gender), alpha = 0.5, adjust=20)
```

```{r}

```



```{r}
write.csv(new_survey_dataset,"new_survey_dataset2.csv", row.names = FALSE)
```



Let’s transform all values into numeric types.

```{r}
new_survey_dataset[is.na(new_survey_dataset)] <- -1

new_survey_dataset$gender[new_survey_dataset$gender == "M"] <- 1
new_survey_dataset$gender[new_survey_dataset$gender == "F"] <- 2
new_survey_dataset$gender[new_survey_dataset$gender == "Non"] <- 3
new_survey_dataset$gender[new_survey_dataset$gender == "trans-F"]<- 4
new_survey_dataset$gender[new_survey_dataset$gender == "trans-M"] <- 5
new_survey_dataset$gender <- as.numeric(new_survey_dataset$gender)

new_survey_dataset$family_history[new_survey_dataset$family_history == "Yes"] <- 1
new_survey_dataset$family_history[new_survey_dataset$family_history == "No"] <- 0
new_survey_dataset$family_history <- as.numeric(new_survey_dataset$family_history)

new_survey_dataset$treatment_seek[new_survey_dataset$treatment_seek == "No"] <- 0
new_survey_dataset$treatment_seek[new_survey_dataset$treatment_seek == "Yes"] <- 1
new_survey_dataset$treatment_seek <- as.numeric(new_survey_dataset$treatment_seek)

new_survey_dataset$work_interference[new_survey_dataset$work_interference == "Never"] <- 0
new_survey_dataset$work_interference[new_survey_dataset$work_interference == "Rarely"] <- 1
new_survey_dataset$work_interference[new_survey_dataset$work_interference == "Sometimes"] <- 2
new_survey_dataset$work_interference[new_survey_dataset$work_interference == "Often"] <- 3
new_survey_dataset$work_interference <- as.numeric(new_survey_dataset$work_interference)


new_survey_dataset$num_employees[new_survey_dataset$num_employees == "1-5"] <- 0
new_survey_dataset$num_employees[new_survey_dataset$num_employees == "6-25"] <- 1
new_survey_dataset$num_employees[new_survey_dataset$num_employees == "26-100"] <- 2
new_survey_dataset$num_employees[new_survey_dataset$num_employees == "100-500"] <- 3
new_survey_dataset$num_employees[new_survey_dataset$num_employees == "500-1000"] <- 4
new_survey_dataset$num_employees[new_survey_dataset$num_employees == "More than 1000"] <- 5
new_survey_dataset$num_employees <- as.numeric(new_survey_dataset$num_employees)

new_survey_dataset$remote_work[new_survey_dataset$remote_work == "No"] <- 0
new_survey_dataset$remote_work[new_survey_dataset$remote_work == "Yes"] <- 1
new_survey_dataset$remote_work <- as.numeric(new_survey_dataset$remote_work)

new_survey_dataset$tech_company[new_survey_dataset$tech_company == "No"] <- 0
new_survey_dataset$tech_company[new_survey_dataset$tech_company == "Yes"] <- 1
new_survey_dataset$tech_company <- as.numeric(new_survey_dataset$tech_company)

new_survey_dataset$employer_benefits[new_survey_dataset$employer_benefits == "No"] <- 0
new_survey_dataset$employer_benefits[new_survey_dataset$employer_benefits == "Yes"] <- 1
new_survey_dataset$employer_benefits[new_survey_dataset$employer_benefits == "Don't know"] <- 3
new_survey_dataset$employer_benefits <- as.numeric(new_survey_dataset$employer_benefits)
 
new_survey_dataset$provided_care_options[new_survey_dataset$provided_care_options == "No"] <- 0
new_survey_dataset$provided_care_options[new_survey_dataset$provided_care_options == "Yes"] <- 1
new_survey_dataset$provided_care_options[new_survey_dataset$provided_care_options == "Not sure"] <- 3
new_survey_dataset$provided_care_options <- as.numeric(new_survey_dataset$provided_care_options) 

new_survey_dataset$employee_wellness_program[new_survey_dataset$employee_wellness_program == "No"] <- 0
new_survey_dataset$employee_wellness_program[new_survey_dataset$employee_wellness_program == "Yes"] <- 1
new_survey_dataset$employee_wellness_program[new_survey_dataset$employee_wellness_program == "Don't know"] <- 3
new_survey_dataset$employee_wellness_program <- as.numeric(new_survey_dataset$employee_wellness_program)

new_survey_dataset$provided_seek_help[new_survey_dataset$provided_seek_help == "No"] <- 0
new_survey_dataset$provided_seek_help[new_survey_dataset$provided_seek_help == "Yes"] <- 1
new_survey_dataset$provided_seek_help[new_survey_dataset$provided_seek_help == "Don't know"] <- 3
new_survey_dataset$provided_seek_help <- as.numeric(new_survey_dataset$provided_seek_help)

new_survey_dataset$anonymity_protection[new_survey_dataset$anonymity_protection == "No"] <- 0
new_survey_dataset$anonymity_protection[new_survey_dataset$anonymity_protection == "Yes"] <- 1
new_survey_dataset$anonymity_protection[new_survey_dataset$anonymity_protection == "Don't know"] <- 3
new_survey_dataset$anonymity_protection <- as.numeric(new_survey_dataset$anonymity_protection)

new_survey_dataset$medical_leave_mh[new_survey_dataset$medical_leave_mh == "Very easy"] <- 0
new_survey_dataset$medical_leave_mh[new_survey_dataset$medical_leave_mh == "Somewhat easy"] <- 1
new_survey_dataset$medical_leave_mh[new_survey_dataset$medical_leave_mh == "Don't know"] <- 2
new_survey_dataset$medical_leave_mh[new_survey_dataset$medical_leave_mh == "Somewhat difficult"] <- 3
new_survey_dataset$medical_leave_mh[new_survey_dataset$medical_leave_mh == "Very difficult"] <- 4
new_survey_dataset$medical_leave_mh <- as.numeric(new_survey_dataset$medical_leave_mh)

new_survey_dataset$mental_health_neg_consequence[new_survey_dataset$mental_health_neg_consequence == "No"] <- 0
new_survey_dataset$mental_health_neg_consequence[new_survey_dataset$mental_health_neg_consequence == "Yes"] <- 1
new_survey_dataset$mental_health_neg_consequence[new_survey_dataset$mental_health_neg_consequence == "Maybe"] <- 3
new_survey_dataset$mental_health_neg_consequence <- as.numeric(new_survey_dataset$mental_health_neg_consequence)

new_survey_dataset$phys_health_neg_consequence[new_survey_dataset$phys_health_neg_consequence == "No"] <- 0
new_survey_dataset$phys_health_neg_consequence[new_survey_dataset$phys_health_neg_consequence == "Yes"] <- 1
new_survey_dataset$phys_health_neg_consequence[new_survey_dataset$phys_health_neg_consequence == "Maybe"] <- 3
new_survey_dataset$phys_health_neg_consequence <- as.numeric(new_survey_dataset$phys_health_neg_consequence)

new_survey_dataset$discussing_mh_coworkers[new_survey_dataset$discussing_mh_coworkers == "No"] <- 0
new_survey_dataset$discussing_mh_coworkers[new_survey_dataset$discussing_mh_coworkers == "Yes"] <- 1
new_survey_dataset$discussing_mh_coworkers[new_survey_dataset$discussing_mh_coworkers == "Some of them"] <- 3
new_survey_dataset$discussing_mh_coworkers <- as.numeric(new_survey_dataset$discussing_mh_coworkers)

new_survey_dataset$discussing_mh_supervisor[new_survey_dataset$discussing_mh_supervisor == "No"] <- 0
new_survey_dataset$discussing_mh_supervisor[new_survey_dataset$discussing_mh_supervisor == "Yes"] <- 1
new_survey_dataset$discussing_mh_supervisor[new_survey_dataset$discussing_mh_supervisor == "Some of them"] <- 3
new_survey_dataset$discussing_mh_supervisor <- as.numeric(new_survey_dataset$discussing_mh_supervisor)

new_survey_dataset$mentalhealthinterview[new_survey_dataset$mentalhealthinterview == "No"] <- 0
new_survey_dataset$mentalhealthinterview[new_survey_dataset$mentalhealthinterview == "Yes"] <- 1
new_survey_dataset$mentalhealthinterview[new_survey_dataset$mentalhealthinterview == "Maybe"] <- 3
new_survey_dataset$mentalhealthinterview <- as.numeric(new_survey_dataset$mentalhealthinterview)

new_survey_dataset$phys_health_interview[new_survey_dataset$phys_health_interview == "No"] <- 0
new_survey_dataset$phys_health_interview[new_survey_dataset$phys_health_interview == "Yes"] <- 1
new_survey_dataset$phys_health_interview[new_survey_dataset$phys_health_interview == "Maybe"] <- 3
new_survey_dataset$phys_health_interview <- as.numeric(new_survey_dataset$phys_health_interview)

new_survey_dataset$mental_vs_physical[new_survey_dataset$mental_vs_physical == "No"] <- 0
new_survey_dataset$mental_vs_physical[new_survey_dataset$mental_vs_physical == "Yes"] <- 1
new_survey_dataset$mental_vs_physical[new_survey_dataset$mental_vs_physical == "Don't know"] <- 3
new_survey_dataset$mental_vs_physical <- as.numeric(new_survey_dataset$mental_vs_physical)

new_survey_dataset$obs_consequence[new_survey_dataset$obs_consequence == "No"] <- 0
new_survey_dataset$obs_consequence[new_survey_dataset$obs_consequence == "Yes"] <- 1
new_survey_dataset$obs_consequence <- as.numeric(new_survey_dataset$obs_consequence)

new_survey_dataset <- as.data.frame(unclass(new_survey_dataset),stringsAsFactors=TRUE)
str(new_survey_dataset)

```



```{r}
new_survey_dataset$comments<- NULL
new_survey_dataset$treatment_seek<- as.factor(new_survey_dataset$treatment_seek)
write.csv(new_survey_dataset,"new_survey_dataset2.csv", row.names = FALSE)

skimmed <- skim(new_survey_dataset)
skimmed


```




